//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCurrency.ServiceReferenceCurrency {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFCurrency")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCurrency.IServiceCurrency")]
    public interface IServiceCurrency {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCurrency/GetData", ReplyAction="http://tempuri.org/IServiceCurrency/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCurrency/GetData", ReplyAction="http://tempuri.org/IServiceCurrency/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCurrency/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceCurrency/GetDataUsingDataContractResponse")]
        WpfCurrency.ServiceReferenceCurrency.CompositeType GetDataUsingDataContract(WpfCurrency.ServiceReferenceCurrency.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCurrency/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceCurrency/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WpfCurrency.ServiceReferenceCurrency.CompositeType> GetDataUsingDataContractAsync(WpfCurrency.ServiceReferenceCurrency.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCurrency/GetCurrencyString", ReplyAction="http://tempuri.org/IServiceCurrency/GetCurrencyStringResponse")]
        string GetCurrencyString(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCurrency/GetCurrencyString", ReplyAction="http://tempuri.org/IServiceCurrency/GetCurrencyStringResponse")]
        System.Threading.Tasks.Task<string> GetCurrencyStringAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCurrencyChannel : WpfCurrency.ServiceReferenceCurrency.IServiceCurrency, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCurrencyClient : System.ServiceModel.ClientBase<WpfCurrency.ServiceReferenceCurrency.IServiceCurrency>, WpfCurrency.ServiceReferenceCurrency.IServiceCurrency {
        
        public ServiceCurrencyClient() {
        }
        
        public ServiceCurrencyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCurrencyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCurrencyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCurrencyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WpfCurrency.ServiceReferenceCurrency.CompositeType GetDataUsingDataContract(WpfCurrency.ServiceReferenceCurrency.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WpfCurrency.ServiceReferenceCurrency.CompositeType> GetDataUsingDataContractAsync(WpfCurrency.ServiceReferenceCurrency.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetCurrencyString(int value) {
            return base.Channel.GetCurrencyString(value);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyStringAsync(int value) {
            return base.Channel.GetCurrencyStringAsync(value);
        }
    }
}
